#!/usr/bin/env node
/**
 * Runs extract-fixtures.js and generate-cases.js for every document listed
 * in sources/sources.json, so a fresh clone (after fetch-sources.js) doesn't
 * need each document extracted/generated by hand.
 *
 * Usage:
 *   node tests/pdf-match/prepare.js [--id <docid>] [--max 10] [--no-render] [--overwrite]
 *
 * --id <docid>   Only prepare this one document (default: all in the manifest).
 * --max <n>      Passed through to generate-cases.js (default: 10).
 * --no-render    Skip page PNG rendering in extract-fixtures.js.
 * --overwrite    Regenerate cases even if cases/<docid>-*.json already exist,
 *                discarding any recorded review state (expected/rejected).
 *                Without this flag, only the generate-cases step is skipped
 *                for that document — extract-fixtures (incl. page PNGs, which
 *                are gitignored and so absent on a fresh clone) always runs.
 *
 * Expects sources/<docid>.pdf (see fetch-sources.js) and sources/<docid>.tei.xml
 * (committed) to already exist for each docid.
 */

import { existsSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { parseArgs } from 'node:util';

const baseDir = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.join(baseDir, '..', '..');
const SOURCES_DIR = path.join(baseDir, 'sources');
const CASES_DIR = path.join(baseDir, 'cases');
const MANIFEST_PATH = path.join(SOURCES_DIR, 'sources.json');

/**
 * Converts an absolute path to a repo-relative, forward-slash path, so
 * values recorded from it (e.g. a fixture's `sourcePath`) stay portable
 * across machines/OSes instead of an absolute Windows path leaking in.
 * @param {string} absPath
 * @returns {string}
 */
function toRepoRelative(absPath) {
  return path.relative(REPO_ROOT, absPath).split(path.sep).join('/');
}

const { values } = parseArgs({
  options: {
    id: { type: 'string' },
    max: { type: 'string', default: '10' },
    'no-render': { type: 'boolean', default: false },
    overwrite: { type: 'boolean', default: false }
  }
});

/**
 * @param {string} docid
 * @returns {boolean} true if cases/<docid>-*.json already exist
 */
function hasExistingCases(docid) {
  if (!existsSync(CASES_DIR)) return false;
  const prefix = `${docid}-`;
  return readdirSync(CASES_DIR).some(f => f.startsWith(prefix) && f.endsWith('.json'));
}

/** @returns {Record<string, unknown>} */
function loadManifest() {
  const raw = JSON.parse(readFileSync(MANIFEST_PATH, 'utf-8'));
  const { _comment, ...entries } = raw;
  return entries;
}

/**
 * Runs a pdf-match script as a child process, inheriting stdio.
 * @param {string} script - Script filename (relative to this directory)
 * @param {string[]} args
 * @returns {boolean} true on exit code 0
 */
function run(script, args) {
  console.log(`\n$ node tests/pdf-match/${script} ${args.join(' ')}`);
  const result = spawnSync(process.execPath, [path.join(baseDir, script), ...args], { stdio: 'inherit', cwd: REPO_ROOT });
  return result.status === 0;
}

const manifest = loadManifest();
const docids = values.id ? [values.id] : Object.keys(manifest);

if (values.id && !manifest[values.id]) {
  console.error(`Unknown docid: ${values.id}`);
  console.error(`Known docids: ${Object.keys(manifest).join(', ')}`);
  process.exit(2);
}

let okCount = 0;
let failedCount = 0;

for (const docid of docids) {
  const pdfPath = path.join(SOURCES_DIR, `${docid}.pdf`);
  const teiPath = path.join(SOURCES_DIR, `${docid}.tei.xml`);

  if (!existsSync(pdfPath)) {
    console.error(`[${docid}] SKIPPED — ${pdfPath} not found, run "npm run pdf-match:fetch" first`);
    failedCount++;
    continue;
  }
  if (!existsSync(teiPath)) {
    console.error(`[${docid}] SKIPPED — ${teiPath} not found`);
    failedCount++;
    continue;
  }
  const extractArgs = ['--pdf', toRepoRelative(pdfPath), '--id', docid];
  if (!values['no-render']) extractArgs.push('--render');
  const extractOk = run('extract-fixtures.js', extractArgs);

  let generateOk = true;
  if (!values.overwrite && hasExistingCases(docid)) {
    console.log(`[${docid}] generate-cases SKIPPED — cases already exist, use --overwrite to regenerate (discards review state)`);
  } else {
    generateOk = extractOk && run('generate-cases.js', ['--tei', toRepoRelative(teiPath), '--pdf-id', docid, '--max', values.max]);
  }

  if (extractOk && generateOk) okCount++;
  else failedCount++;
}

console.log(`\n${okCount} ok, ${failedCount} failed`);
process.exit(failedCount > 0 ? 1 : 0);
