"""
Migration 003: Remove RNG Schema Files

Removes RNG schema files from the database that were generated by the old
RNG extractor. These files are no longer needed as the RNG converter plugin
now generates schemas on-demand for download.

Before: Database contains RNG schema files with doc_id pattern "schema-rng-*"
After: RNG schema files are removed from database
"""

import sqlite3
from fastapi_app.lib.core.migrations.base import Migration


class Migration003RemoveSchemaFiles(Migration):
    """
    Remove RNG schema files from database.

    The old RNG extractor stored schema files in the database with
    doc_id pattern "schema-rng-{variant}". These are no longer needed
    as the RNG converter plugin now generates schemas on-demand.
    """

    @property
    def version(self) -> int:
        """Migration version number."""
        return 3

    @property
    def description(self) -> str:
        """Human-readable description."""
        return "Remove RNG schema files from database"

    def check_can_apply(self, conn: sqlite3.Connection) -> bool:
        """
        Check if migration can be applied.

        Args:
            conn: SQLite connection

        Returns:
            True if there are schema files to remove, False otherwise
        """
        # Check if file_metadata table exists
        cursor = conn.execute("""
            SELECT name FROM sqlite_master
            WHERE type='table' AND name='file_metadata'
        """)
        if not cursor.fetchone():
            self.logger.info("file_metadata table does not exist - migration not needed")
            return False

        # Check for schema files
        cursor = conn.execute("""
            SELECT COUNT(*) FROM file_metadata
            WHERE doc_id LIKE 'schema-rng-%'
        """)
        count = cursor.fetchone()[0]

        if count == 0:
            self.logger.info("No schema files found - migration not needed")
            return False

        self.logger.info(f"Found {count} schema file(s) to remove")
        return True

    def upgrade(self, conn: sqlite3.Connection) -> None:
        """
        Apply the migration - remove schema files.

        Args:
            conn: SQLite connection (in transaction)
        """
        self.logger.info("Removing RNG schema files from database")

        # Get all schema file IDs and stable IDs before deletion
        cursor = conn.execute("""
            SELECT id, stable_id, doc_id
            FROM file_metadata
            WHERE doc_id LIKE 'schema-rng-%'
        """)
        schema_files = cursor.fetchall()

        if not schema_files:
            self.logger.info("No schema files found")
            return

        self.logger.info(f"Removing {len(schema_files)} schema file(s)")

        # Delete from file_metadata table
        conn.execute("""
            DELETE FROM file_metadata
            WHERE doc_id LIKE 'schema-rng-%'
        """)

        deleted_count = conn.total_changes
        self.logger.info(f"Deleted {deleted_count} schema file record(s) from database")

        # Log details of removed files
        for file_id, stable_id, doc_id in schema_files:
            self.logger.debug(f"Removed schema file: doc_id={doc_id}, id={file_id}, stable_id={stable_id}")

        self.logger.info("Migration 003 complete")

    def downgrade(self, conn: sqlite3.Connection) -> None:
        """
        Revert the migration.

        Note: This cannot restore the actual schema files as they were generated
        and not stored. This is intentionally a no-op.

        Args:
            conn: SQLite connection (in transaction)
        """
        self.logger.info("Reverting migration 003")
        self.logger.warning(
            "Cannot restore deleted schema files - they were generated content. "
            "Schema files can be regenerated using the RNG converter plugin."
        )
        self.logger.info("Migration 003 reverted (no-op)")
